### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by gbrow004** [YoRyan/nuxhash#103]
Getting this error in both the GUI and the terminal. On Ubuntu 21.04 with nvidia driver 460.91.03 and RTX3090. I also tried revising the nicehash.py as described here with no effect: https://askubuntu.com/questions/1289767/nuxhash-mining-on-linux-for-nicehash-miner

Here's the full output error:
`Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 8, in <module>
    sys.exit(nuxhashd())
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/daemon.py", line 103, in main
    nx_benchmarks = run_missing_benchmarks(
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/daemon.py", line 168, in run_missing_benchmarks
    miner.unload()
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/miners/excavator.py", line 381, in unload
    self.server.stop()
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/miners/excavator.py", line 143, in stop
    self.send_command('unsubscribe', [])
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/miners/excavator.py", line 165, in send_command
    with socket.create_connection(self._address, self.TIMEOUT) as s:
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2021-08-11 17:23:28,774 CRITICAL: Crash! Killing all miners.
Killed
`

**Comment by pleymor** [comment]
Same error here. Everytime I try again, ist always crashing at `excavator_daggerhashimoto`:

```
  excavator_cryptonightV8:   5.82 MH/s                      
  excavator_pascal:   0.00  H/s                      
  excavator_daggerhashimoto: failed to complete benchmark     
  excavator_daggerhashimoto_pascal: failed to complete benchmark     
  excavator_neoscrypt: failed to complete benchmark     
  excavator_decred: failed to complete benchmark     
  excavator_blake2s: failed to complete benchmark     
  excavator_daggerhashimoto_decred: failed to complete benchmark     
  excavator_keccak: failed to complete benchmark     
  excavator_lyra2z: failed to complete benchmark     
  excavator_lyra2rev2: failed to complete benchmark     
  excavator_cryptonightV7: failed to complete benchmark     
  excavator_x16r: failed to complete benchmark     
  excavator_equihash: failed to complete benchmark     
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 8, in <module>
    sys.exit(nuxhashd())
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/daemon.py", line 103, in main
    nx_benchmarks = run_missing_benchmarks(
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/daemon.py", line 168, in run_missing_benchmarks
    miner.unload()
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/miners/excavator.py", line 381, in unload
    self.server.stop()
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/miners/excavator.py", line 143, in stop
    self.send_command('unsubscribe', [])
  File "/usr/local/lib/python3.9/dist-packages/nuxhash/miners/excavator.py", line 165, in send_command
    with socket.create_connection(self._address, self.TIMEOUT) as s:
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2021-10-20 20:48:38,381 CRITICAL: Crash! Killing all miners.
[1]    112569 killed     nuxhashd --show-mining
```

**Comment by willstahl** [comment]
FYI I noticed I got this error when I didn't start up nuxhashd as sudo. Hope that fixes it for you!

**Comment by supovic1** [comment]
I have been facing the same issue (crashing at `excavator_daggerhashimoto`). I have been using `idkau`'s fork due to issues with wxPython on Ubuntu 18.04. 
I figure it out by uninstalling that fork and installing the original `YoRyan`'s version which works fine in terminal/ Hope it helps you as well.
