### ISSUE TITLE
Nuxhash Startup Failure

### ISSUE THREAD

**Issue by Angu0083** [YoRyan/nuxhash#104]
Worker name: dem
Region (eu/usa/hk/jp/in/br): eu

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   633  100   633    0     0   3314      0 --:--:-- --:--:-- --:--:--  3314
100 5830k  100 5830k    0     0  13.8M      0 --:--:-- --:--:-- --:--:--  247M
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 104, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 124, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2021-08-19 07:20:58,212 CRITICAL: Crash! Killing all miners.
Killed

**Comment by Xfox0ne** [comment]
Same issue

THANKS FOR NOT EVEN LETTING ONE KNOW WHAT THE ERROR IS, PIECE OF CODE

**Comment by cprn** [comment]
You can set a conditional breakpoint on `excavator.py`, line 123, and check the `poll()` result when it crashes. Returned value should be an int representing that's described in a "return codes" section of the library specification.
