### ISSUE TITLE
nuxhash-gui not working in Zorin OS 16

### ISSUE THREAD

**Issue by IAmKota** [YoRyan/nuxhash#105]
Zorin OS 16 is using debian. I tried to install pythonwx but im not sure where to go when it comes to installing it. I tried to just install it via terminal but it didnt work. Help?

nuxhash-gui
Traceback (most recent call last):
  File "/usr/local/bin/nuxhash-gui", line 8, in <module>
    sys.exit(nuxhash_gui())
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/__init__.py", line 6, in nuxhash_gui
    from nuxhash.gui.main import main
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/main.py", line 9, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

**Comment by yonderbread** [comment]
Trying installing `python3-wxgtk4.0` with apt in your terminal, then attempt running the client again:
`sudo apt update && sudo apt install -y python3-wxgtk4.0`
[Package details](https://packages.ubuntu.com/hirsute/python3-wxgtk4.0)
