### ISSUE TITLE
GUI failed to start.

### ISSUE THREAD

**Issue by Napenthes** [YoRyan/nuxhash#109]
Ubuntu 19.10 - GEForce GTX 1060
The GUI failed to start with the following errors. 

Traceback (most recent call last):
  File "/usr/local/bin/nuxhash-gui", line 8, in <module> sys.exit(nuxhash_gui())
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/__init__.py", line 6, in nuxhash_gui from nuxhash.gui.main import main
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/main.py", line 9, in <module> import wx
ModuleNotFoundError: No module named 'wx'

**Comment by henriktre** [comment]
you need to install some sort of wx tools, im on arch, so i cant give you specific command. 
have you tried installing the package specified in the quick start?
`sudo apt install python3-wxgtk4.0` ?

**Comment by Zuiron** [comment]
you need the package "python-wxpython"

**Comment by Kief5555** [comment]
> you need to install some sort of wx tools, im on arch, so i cant give you specific command. have you tried installing the package specified in the quick start? `sudo apt install python3-wx
<img width="804" alt="Screen Shot 2022-01-06 at 4 32 30 PM" src="https://user-images.githubusercontent.com/67562560/148471863-2527e201-297f-474a-865a-7e6f93196262.png">
gtk4.0` ? did that, still failed

**Comment by cprn** [comment]
Currently the simplest solution is to switch to [idkau's fork](https://github.com/idkau/nuxhash). He fixed `wx` versions incompatibility. Either that or you can patch in his changes yourself.
