### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by ToMattBan** [YoRyan/nuxhash#110]
When I try to run (not the gui, but the cli version), I got this error after some download:

```CUDA device: NVIDIA GeForce RTX 3060 (GPU-8eccedee-3323-a9f7-a82f-f1b2397ad1a2)
  excavator_blake2s:   3.49 TH/s                      
  excavator_neoscrypt:  72.34 MH/s                      
  excavator_decred:   0.00  H/s                      
  excavator_x16r:   0.00  H/s                      
  excavator_daggerhashimoto_decred:   0.00  H/s,   0.00  H/s                      
  excavator_lyra2z:   0.00  H/s                      
  excavator_daggerhashimoto: failed to complete benchmark     
  excavator_cryptonightV7: failed to complete benchmark     
  excavator_daggerhashimoto_pascal: failed to complete benchmark     
  excavator_keccak: failed to complete benchmark     
  excavator_pascal: failed to complete benchmark     
  excavator_equihash: failed to complete benchmark     
  excavator_lyra2rev2: failed to complete benchmark     
  excavator_cryptonightV8: failed to complete benchmark     
Traceback (most recent call last):
  File "/usr/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/lib/python3.6/site-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/lib/python3.6/site-packages/nuxhash/daemon.py", line 104, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/lib/python3.6/site-packages/nuxhash/daemon.py", line 168, in run_missing_benchmarks
    miner.unload()
  File "/usr/lib/python3.6/site-packages/nuxhash/miners/excavator.py", line 381, in unload
    self.server.stop()
  File "/usr/lib/python3.6/site-packages/nuxhash/miners/excavator.py", line 143, in stop
    self.send_command('unsubscribe', [])
  File "/usr/lib/python3.6/site-packages/nuxhash/miners/excavator.py", line 165, in send_command
    with socket.create_connection(self._address, self.TIMEOUT) as s:
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2021-10-26 10:13:53,280 CRITICAL: Crash! Killing all miners.
Killed
```

**Comment by willstahl** [comment]
FYI I noticed I got this error when I didn't start up nuxhashd as sudo. Hope that fixes it for you!

**Comment by Jacobsolawetz** [comment]
Likewise ```Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 8, in <module>
    sys.exit(nuxhashd())
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/daemon.py", line 103, in main
    nx_benchmarks = run_missing_benchmarks(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/daemon.py", line 168, in run_missing_benchmarks
    miner.unload()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/miners/excavator.py", line 381, in unload
    self.server.stop()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/miners/excavator.py", line 143, in stop
    self.send_command('unsubscribe', [])
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/miners/excavator.py", line 165, in send_command
    with socket.create_connection(self._address, self.TIMEOUT) as s:
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2022-03-08 16:42:08,496 CRITICAL: Crash! Killing all miners.```
