### ISSUE TITLE
Unable to benchmark or mine

### ISSUE THREAD

**Issue by FiremanDJ** [YoRyan/nuxhash#113]
The GUI opens with a warning that locale 'en_US' cannot be set.
It saves it's settings, but benchmarking does nothing and mining is locked out.

Starting via nuxhashd fails as below.

Ubuntu 20.04

```
***@***:~$ nuxhashd
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 8, in <module>
    sys.exit(nuxhashd())
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/daemon.py", line 103, in main
    nx_benchmarks = run_missing_benchmarks(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/miners/excavator.py", line 124, in start
    raise miner.Miner18:20:28: Cannot set locale to language "English (U.S.)".
18:20:28: lStartFailed
nuxhash.miners.miner.MinerStartFailed
2021-11-14 18:21:58,575 CRITICAL: Crash! Killing all miners.
Killed
```

```
***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WA***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)
***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNIN***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while a***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Foundllocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not FoundG **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Found
(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not FoundRNING **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Found010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Found
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Foundnode entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Found
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhr***@***~$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.010: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:41025): Gtk-WARNING **: 18:19:08.011: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Foundest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Found
```

**Comment by cprn** [comment]
Well, first of all, what does your `locale` say? I didn't know this app requires en_US but if you for some reason don't want to install US English system-wide you can set it up on runtime, try running the binary like so:
```sh
LC_ALL=en_US.UTF-8 nuxhashd       # or
LC_ALL=en_US.UTF-8 nuxhash-gui
```

**Comment by mpouleijn** [comment]
I have the same issue with a clean Ubuntu 20.04 machine also with `LC_ALL=en_US.UTF-8 nuxhashd` I will get the same errors

**Comment by pvy** [comment]
the same problem.
Error after boot (Exception: 404: Not Found) is an attempt to log in to my rig:
https://api2.nicehash.com/main/api/v2/mining/external/MYURL/rigs/
(of course the MYURL is the correct wallet address)

Rig does not exist. How can I create it without the original client?

**Comment by cprn** [comment]
Idk about locale issue but nuxhash-gui doesn't work right now due to wx changes. You can use [idkau's fork](https://github.com/idkau/nuxhash) that solves the wx issue.

**Comment by benthetechguy** [comment]
@cprn, please don't advertise forks of a program in issues that are unrelated to what the fork fixes.

**Comment by cprn** [comment]
@benthetechguy My bad, I didn't read the log carefully and assumed he's hitting the API mismatch like most of the folks recently.
