### ISSUE TITLE
404 not found on get_balances

### ISSUE THREAD

**Issue by soulslicer** [YoRyan/nuxhash#115]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/nicehash.py", line 27, in get_balances
    'GET', f'/main/api/v2/mining/external/{address}/rigs/', '', None)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Found
```

After i entered my Nicehash address. Did some API in nicehash change again?

**Comment by huntertj** [comment]
https://github.com/YoRyan/nuxhash/pull/58 fixes it

**Comment by soulslicer** [comment]
Still doesnt work, now it says API keys required
