### ISSUE TITLE
Crash on startup since update on Pop!OS

### ISSUE THREAD

**Issue by JVTEAM** [YoRyan/nuxhash#127]
I'm unable to launch nuxhashd since Pop!OS upgraded it's version.

Intel processor with Nvidia GPU

Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 8, in <module>
    sys.exit(nuxhashd())
  File "/usr/local/lib/python3.10/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.10/dist-packages/nuxhash/daemon.py", line 72, in main
    all_devices = nvidia_devices()
  File "/usr/local/lib/python3.10/dist-packages/nuxhash/devices/nvidia.py", line 26, in enumerate_devices
    raw = subprocess.check_output(['nvidia-smi', '--query', '--xml-format'])
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nvidia-smi', '--query', '--xml-format']' returned non-zero exit status 255.
2022-08-18 10:29:33,861 CRITICAL: Crash! Killing all miners.
Killed

**Comment by JVTEAM** [comment]
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '
Traceback (most recent call last):
  File "/usr/local/bin/nuxhash-gui", line 8, in <module>
    sys.exit(nuxhash_gui())
  File "/usr/local/lib/python3.10/dist-packages/nuxhash/__init__.py", line 7, in nuxhash_gui
    main()
  File "/usr/local/lib/python3.10/dist-packages/nuxhash/gui/main.py", line 146, in main
    frame = MainWindow(None, title='nuxhash')
  File "/usr/local/lib/python3.10/dist-packages/nuxhash/gui/main.py", line 42, in __init__
    MiningScreen(notebook, devices=self._Devices),
  File "/usr/local/lib/python3.10/dist-packages/nuxhash/gui/mining.py", line 57, in __init__
    self._Timer.Start(milliseconds=BALANCE_UPDATE_MIN*60*1e3)
TypeError: Timer.Start(): argument 'milliseconds' has unexpected type 'float'
Killed
