### ISSUE TITLE
Benchmark Failing on Ubuntu 18.04 with Python 3.6

### ISSUE THREAD

**Issue by billsboard** [YoRyan/nuxhash#15]
The actual benchmark of the cards works fine, but the writing of the benchmarks to the file causes a `TypeError: 'map' object is not subscriptable` error in the python script

Full error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0a0', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash-1.0.0a0-py3.6.egg/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash-1.0.0a0-py3.6.egg/nuxhash/daemon.py", line 93, in main
    session.run()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash-1.0.0a0-py3.6.egg/nuxhash/daemon.py", line 233, in run
    self._scheduler.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash-1.0.0a0-py3.6.egg/nuxhash/daemon.py", line 262, in _switch_algos
    for device in self._devices}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash-1.0.0a0-py3.6.egg/nuxhash/daemon.py", line 262, in <dictcomp>
    for device in self._devices}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash-1.0.0a0-py3.6.egg/nuxhash/daemon.py", line 261, in <dictcomp>
    for algorithm in self._algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash-1.0.0a0-py3.6.egg/nuxhash/daemon.py", line 257, in revenue
    for i in range(len(algorithm.algorithms))])
  File "/usr/local/lib/python3.6/dist-packages/nuxhash-1.0.0a0-py3.6.egg/nuxhash/daemon.py", line 257, in <listcomp>
    for i in range(len(algorithm.algorithms))])
TypeError: 'map' object is not subscriptable
```

**Comment by YoRyan** [comment]
Sorry about the mess! Leftovers from the Python 3 move.
