### ISSUE TITLE
Error when doing nuxhashd

### ISSUE THREAD

**Issue by osu** [YoRyan/nuxhash#23]
Here is the error 
```root@scw-relaxed-lamport:~# nuxhashd
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 3, in                         nuxhashd
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 73, in m                        ain
    all_devices = nvidia_devices()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/devices/nvidia.py", line                         26, in enumerate_devices
    raw = subprocess.check_output(['nvidia-smi', '--query', '--xml-format'])
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nvidia-smi', '--query', '--xml-format'                        ]' returned non-zero exit status 9.
2019-04-08 12:37:55,635 CRITICAL: Crash! Killing all miners.
Killed

**Comment by osu** [comment]
I already got python3-wxgtk4.0 and ocl-icd-libopencl1 downloaded

**Comment by YoRyan** [comment]
What happens when you run `nvidia-smi --query --xml-format` in the terminal?

**Comment by UbuntuSteve** [comment]
Would like to use your program but it will not work.
 nuxhash-gui
Traceback (most recent call last):
  File "/usr/local/bin/nuxhash-gui", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhash-gui')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 6, in nuxhash_gui
    from nuxhash.gui.main import main
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/main.py", line 9, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

I have tried a lot of things to get wx working but I welcome to try more things.

Thank you!

**Comment by YoRyan** [comment]
Distribution? Not all of them include wxPython 4.0.

**Comment by UbuntuSteve** [comment]
I am running the latest Ubuntu. Most packages offer to download missing dependencies. Are you going to provide a link to where I can get what I need?
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Thank you. I really want to run your software.

**Comment by UbuntuSteve** [comment]
Solved my own problem https://tutorialforlinux.com/2018/05/05/how-to-install-python-3-wxpython-for-ubuntu-18-04-bionic-easy-guide/2/

**Comment by UbuntuSteve** [comment]
Now I get:
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 105, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 145, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 380, in load
    self.server.start()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 125, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2019-04-09 19:33:31,248 CRITICAL: Crash! Killing all miners.
Killed

And with nuxhash-gui I get a menu that wants me to benchmark but just sits there and I get:

nuxhash-gui
/home/steve/.local/lib/python3.6/site-packages/wx/lib/pubsub/__init__.py:25: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  wx.wxPyDeprecationWarning)
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(nuxhash-gui:4926): Gtk-CRITICAL **: 19:35:28.941: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.941: gtk_widget_size_allocate(): attempt to allocate widget with width 12 and height -12

(nuxhash-gui:4926): Gtk-CRITICAL **: 19:35:28.941: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(nuxhash-gui:4926): Gtk-CRITICAL **: 19:35:28.944: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.944: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.944: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.944: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.944: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.944: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.944: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.953: Negative content width -15 (allocation 1, extents 8x8) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.966: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:4926): Gtk-WARNING **: 19:35:28.966: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/benchmarks.py", line 258, in run
    miner.load()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 380, in load
    self.server.start()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 125, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed

The GUI just sits there doing nothing an cancel does not work

**Comment by YoRyan** [comment]
Run `~/.config/nuxhash/excavator/excavator -i 127.0.0.1 -p 5001` in a terminal, what happens?

By the way, if this is an unrelated bug, we should consider opening a separate thread.

**Comment by UbuntuSteve** [comment]
I have no clue if the failures are related.  Is anyone running this successfully?  Will it run on OpenSuse?
I really don't want to dump Ubuntu for Win 10 Just so that I can run a Nicehash miner.

You are the programmer, right?  You tell us if you want a new thread.  You are the authority here.

**Comment by YoRyan** [comment]
Suse? Aren't you running Ubuntu 18.04? I developed this project on Ubuntu 18.04 and Fedora 29, for the record.

Look, lots of people are using this software successfully, as evidenced by the donation fees piling up in my NiceHash balance. Your issues could involve anything from the Nvidia driver to the excavator program that a little Python package like nuxhash has no control over. I need some more information to help you solve this.

**Comment by UbuntuSteve** [comment]
I have several machines..  One of them is running OpenSuse but no use trying there unless you are sure it would work.  I have given you the error messages from the Ubuntu machine. What else do you need?
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by UbuntuSteve** [comment]
nvidia-smi --query --xml-format
<?xml version="1.0" ?>
<!DOCTYPE nvidia_smi_log SYSTEM "nvsmi_device_v9.dtd">
<nvidia_smi_log>
	<timestamp>Wed Apr 10 16:36:35 2019</timestamp>
	<driver_version>390.116</driver_version>
	<attached_gpus>2</attached_gpus>
	<gpu id="00000000:05:00.0">
		<product_name>GeForce GTX 1050 Ti</product_name>
		<product_brand>GeForce</product_brand>
		<display_mode>Enabled</display_mode>
		<display_active>Enabled</display_active>
		<persistence_mode>Disabled</persistence_mode>
		<accounting_mode>Disabled</accounting_mode>
		<accounting_mode_buffer_size>4000</accounting_mode_buffer_size>
		<driver_model>
			<current_dm>N/A</current_dm>
			<pending_dm>N/A</pending_dm>
		</driver_model>
		<serial>N/A</serial>
		<uuid>GPU-e8ae7a0f-82c2-d60e-6f21-55e26ca8e9d6</uuid>
		<minor_number>0</minor_number>
		<vbios_version>86.07.39.40.99</vbios_version>
		<multigpu_board>No</multigpu_board>
		<board_id>0x500</board_id>
		<gpu_part_number>N/A</gpu_part_number>
		<inforom_version>
			<img_version>G001.0000.01.04</img_version>
			<oem_object>1.1</oem_object>
			<ecc_object>N/A</ecc_object>
			<pwr_object>N/A</pwr_object>
		</inforom_version>
		<gpu_operation_mode>
			<current_gom>N/A</current_gom>
			<pending_gom>N/A</pending_gom>
		</gpu_operation_mode>
		<gpu_virtualization_mode>
			<virtualization_mode>None</virtualization_mode>
		</gpu_virtualization_mode>
		<pci>
			<pci_bus>05</pci_bus>
			<pci_device>00</pci_device>
			<pci_domain>0000</pci_domain>
			<pci_device_id>1C8210DE</pci_device_id>
			<pci_bus_id>00000000:05:00.0</pci_bus_id>
			<pci_sub_system_id>37631458</pci_sub_system_id>
			<pci_gpu_link_info>
				<pcie_gen>
					<max_link_gen>2</max_link_gen>
					<current_link_gen>1</current_link_gen>
				</pcie_gen>
				<link_widths>
					<max_link_width>16x</max_link_width>
					<current_link_width>16x</current_link_width>
				</link_widths>
			</pci_gpu_link_info>
			<pci_bridge_chip>
				<bridge_chip_type>N/A</bridge_chip_type>
				<bridge_chip_fw>N/A</bridge_chip_fw>
			</pci_bridge_chip>
			<replay_counter>0</replay_counter>
			<tx_util>1000 KB/s</tx_util>
			<rx_util>7000 KB/s</rx_util>
		</pci>
		<fan_speed>0 %</fan_speed>
		<performance_state>P8</performance_state>
		<clocks_throttle_reasons>
			<clocks_throttle_reason_gpu_idle>Active</clocks_throttle_reason_gpu_idle>
			<clocks_throttle_reason_applications_clocks_setting>Not Active</clocks_throttle_reason_applications_clocks_setting>
			<clocks_throttle_reason_sw_power_cap>Not Active</clocks_throttle_reason_sw_power_cap>
			<clocks_throttle_reason_hw_slowdown>Not Active</clocks_throttle_reason_hw_slowdown>
			<clocks_throttle_reason_hw_thermal_slowdown>Not Active</clocks_throttle_reason_hw_thermal_slowdown>
			<clocks_throttle_reason_hw_power_brake_slowdown>Not Active</clocks_throttle_reason_hw_power_brake_slowdown>
			<clocks_throttle_reason_sync_boost>Not Active</clocks_throttle_reason_sync_boost>
			<clocks_throttle_reason_sw_thermal_slowdown>Not Active</clocks_throttle_reason_sw_thermal_slowdown>
			<clocks_throttle_reason_display_clocks_setting>Not Active</clocks_throttle_reason_display_clocks_setting>
		</clocks_throttle_reasons>
		<fb_memory_usage>
			<total>4031 MiB</total>
			<used>328 MiB</used>
			<free>3703 MiB</free>
		</fb_memory_usage>
		<bar1_memory_usage>
			<total>256 MiB</total>
			<used>6 MiB</used>
			<free>250 MiB</free>
		</bar1_memory_usage>
		<compute_mode>Default</compute_mode>
		<utilization>
			<gpu_util>2 %</gpu_util>
			<memory_util>7 %</memory_util>
			<encoder_util>0 %</encoder_util>
			<decoder_util>0 %</decoder_util>
		</utilization>
		<encoder_stats>
			<session_count>0</session_count>
			<average_fps>0</average_fps>
			<average_latency>0</average_latency>
		</encoder_stats>
		<ecc_mode>
			<current_ecc>N/A</current_ecc>
			<pending_ecc>N/A</pending_ecc>
		</ecc_mode>
		<ecc_errors>
			<volatile>
				<single_bit>
					<device_memory>N/A</device_memory>
					<register_file>N/A</register_file>
					<l1_cache>N/A</l1_cache>
					<l2_cache>N/A</l2_cache>
					<texture_memory>N/A</texture_memory>
					<texture_shm>N/A</texture_shm>
					<cbu>N/A</cbu>
					<total>N/A</total>
				</single_bit>
				<double_bit>
					<device_memory>N/A</device_memory>
					<register_file>N/A</register_file>
					<l1_cache>N/A</l1_cache>
					<l2_cache>N/A</l2_cache>
					<texture_memory>N/A</texture_memory>
					<texture_shm>N/A</texture_shm>
					<cbu>N/A</cbu>
					<total>N/A</total>
				</double_bit>
			</volatile>
			<aggregate>
				<single_bit>
					<device_memory>N/A</device_memory>
					<register_file>N/A</register_file>
					<l1_cache>N/A</l1_cache>
					<l2_cache>N/A</l2_cache>
					<texture_memory>N/A</texture_memory>
					<texture_shm>N/A</texture_shm>
					<cbu>N/A</cbu>
					<total>N/A</total>
				</single_bit>
				<double_bit>
					<device_memory>N/A</device_memory>
					<register_file>N/A</register_file>
					<l1_cache>N/A</l1_cache>
					<l2_cache>N/A</l2_cache>
					<texture_memory>N/A</texture_memory>
					<texture_shm>N/A</texture_shm>
					<cbu>N/A</cbu>
					<total>N/A</total>
				</double_bit>
			</aggregate>
		</ecc_errors>
		<retired_pages>
			<multiple_single_bit_retirement>
				<retired_count>N/A</retired_count>
				<retired_page_addresses>N/A</retired_page_addresses>
			</multiple_single_bit_retirement>
			<double_bit_retirement>
				<retired_count>N/A</retired_count>
				<retired_page_addresses>N/A</retired_page_addresses>
			</double_bit_retirement>
			<pending_retirement>N/A</pending_retirement>
		</retired_pages>
		<temperature>
			<gpu_temp>49 C</gpu_temp>
			<gpu_temp_max_threshold>102 C</gpu_temp_max_threshold>
			<gpu_temp_slow_threshold>99 C</gpu_temp_slow_threshold>
			<gpu_temp_max_gpu_threshold>N/A</gpu_temp_max_gpu_threshold>
			<memory_temp>N/A</memory_temp>
			<gpu_temp_max_mem_threshold>N/A</gpu_temp_max_mem_threshold>
		</temperature>
		<power_readings>
			<power_state>P8</power_state>
			<power_management>Supported</power_management>
			<power_draw>N/A</power_draw>
			<power_limit>72.00 W</power_limit>
			<default_power_limit>72.00 W</default_power_limit>
			<enforced_power_limit>72.00 W</enforced_power_limit>
			<min_power_limit>52.50 W</min_power_limit>
			<max_power_limit>75.00 W</max_power_limit>
		</power_readings>
		<clocks>
			<graphics_clock>151 MHz</graphics_clock>
			<sm_clock>151 MHz</sm_clock>
			<mem_clock>405 MHz</mem_clock>
			<video_clock>544 MHz</video_clock>
		</clocks>
		<applications_clocks>
			<graphics_clock>N/A</graphics_clock>
			<mem_clock>N/A</mem_clock>
		</applications_clocks>
		<default_applications_clocks>
			<graphics_clock>N/A</graphics_clock>
			<mem_clock>N/A</mem_clock>
		</default_applications_clocks>
		<max_clocks>
			<graphics_clock>1936 MHz</graphics_clock>
			<sm_clock>1936 MHz</sm_clock>
			<mem_clock>3504 MHz</mem_clock>
			<video_clock>1708 MHz</video_clock>
		</max_clocks>
		<max_customer_boost_clocks>
			<graphics_clock>N/A</graphics_clock>
		</max_customer_boost_clocks>
		<clock_policy>
			<auto_boost>N/A</auto_boost>
			<auto_boost_default>N/A</auto_boost_default>
		</clock_policy>
		<supported_clocks>N/A</supported_clocks>
		<processes>
			<process_info>
				<pid>3003</pid>
				<type>G</type>
				<process_name>/usr/lib/xorg/Xorg</process_name>
				<used_memory>18 MiB</used_memory>
			</process_info>
			<process_info>
				<pid>3099</pid>
				<type>G</type>
				<process_name>/usr/bin/gnome-shell</process_name>
				<used_memory>48 MiB</used_memory>
			</process_info>
			<process_info>
				<pid>3297</pid>
				<type>G</type>
				<process_name>/usr/lib/xorg/Xorg</process_name>
				<used_memory>121 MiB</used_memory>
			</process_info>
			<process_info>
				<pid>3575</pid>
				<type>G</type>
				<process_name>/usr/bin/gnome-shell</process_name>
				<used_memory>104 MiB</used_memory>
			</process_info>
			<process_info>
				<pid>4545</pid>
				<type>G</type>
				<process_name>/opt/google/chrome/chrome --type=gpu-process --field-trial-handle=1203743215467796045,13468618957907894243,131072 --enable-crash-reporter=bb1377b9-1963-4de9-8e66-045d9a7dd7a3, --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --enable-crash-reporter=bb1377b9-1963-4de9-8e66-045d9a7dd7a3, --service-request-channel-token=17178544975993822337</process_name>
				<used_memory>32 MiB</used_memory>
			</process_info>
		</processes>
		<accounted_processes>
		</accounted_processes>
	</gpu>

	<gpu id="00000000:22:00.0">
		<product_name>GeForce GTX 1050 Ti</product_name>
		<product_brand>GeForce</product_brand>
		<display_mode>Disabled</display_mode>
		<display_active>Disabled</display_active>
		<persistence_mode>Disabled</persistence_mode>
		<accounting_mode>Disabled</accounting_mode>
		<accounting_mode_buffer_size>4000</accounting_mode_buffer_size>
		<driver_model>
			<current_dm>N/A</current_dm>
			<pending_dm>N/A</pending_dm>
		</driver_model>
		<serial>N/A</serial>
		<uuid>GPU-c0adaaa2-5e1f-4156-cb0d-813b201249cd</uuid>
		<minor_number>1</minor_number>
		<vbios_version>86.07.39.40.99</vbios_version>
		<multigpu_board>No</multigpu_board>
		<board_id>0x2200</board_id>
		<gpu_part_number>N/A</gpu_part_number>
		<inforom_version>
			<img_version>G001.0000.01.04</img_version>
			<oem_object>1.1</oem_object>
			<ecc_object>N/A</ecc_object>
			<pwr_object>N/A</pwr_object>
		</inforom_version>
		<gpu_operation_mode>
			<current_gom>N/A</current_gom>
			<pending_gom>N/A</pending_gom>
		</gpu_operation_mode>
		<gpu_virtualization_mode>
			<virtualization_mode>None</virtualization_mode>
		</gpu_virtualization_mode>
		<pci>
			<pci_bus>22</pci_bus>
			<pci_device>00</pci_device>
			<pci_domain>0000</pci_domain>
			<pci_device_id>1C8210DE</pci_device_id>
			<pci_bus_id>00000000:22:00.0</pci_bus_id>
			<pci_sub_system_id>37631458</pci_sub_system_id>
			<pci_gpu_link_info>
				<pcie_gen>
					<max_link_gen>2</max_link_gen>
					<current_link_gen>1</current_link_gen>
				</pcie_gen>
				<link_widths>
					<max_link_width>16x</max_link_width>
					<current_link_width>16x</current_link_width>
				</link_widths>
			</pci_gpu_link_info>
			<pci_bridge_chip>
				<bridge_chip_type>N/A</bridge_chip_type>
				<bridge_chip_fw>N/A</bridge_chip_fw>
			</pci_bridge_chip>
			<replay_counter>0</replay_counter>
			<tx_util>0 KB/s</tx_util>
			<rx_util>0 KB/s</rx_util>
		</pci>
		<fan_speed>0 %</fan_speed>
		<performance_state>P8</performance_state>
		<clocks_throttle_reasons>
			<clocks_throttle_reason_gpu_idle>Active</clocks_throttle_reason_gpu_idle>
			<clocks_throttle_reason_applications_clocks_setting>Not Active</clocks_throttle_reason_applications_clocks_setting>
			<clocks_throttle_reason_sw_power_cap>Not Active</clocks_throttle_reason_sw_power_cap>
			<clocks_throttle_reason_hw_slowdown>Not Active</clocks_throttle_reason_hw_slowdown>
			<clocks_throttle_reason_hw_thermal_slowdown>Not Active</clocks_throttle_reason_hw_thermal_slowdown>
			<clocks_throttle_reason_hw_power_brake_slowdown>Not Active</clocks_throttle_reason_hw_power_brake_slowdown>
			<clocks_throttle_reason_sync_boost>Not Active</clocks_throttle_reason_sync_boost>
			<clocks_throttle_reason_sw_thermal_slowdown>Not Active</clocks_throttle_reason_sw_thermal_slowdown>
			<clocks_throttle_reason_display_clocks_setting>Not Active</clocks_throttle_reason_display_clocks_setting>
		</clocks_throttle_reasons>
		<fb_memory_usage>
			<total>4040 MiB</total>
			<used>2 MiB</used>
			<free>4038 MiB</free>
		</fb_memory_usage>
		<bar1_memory_usage>
			<total>256 MiB</total>
			<used>4 MiB</used>
			<free>252 MiB</free>
		</bar1_memory_usage>
		<compute_mode>Default</compute_mode>
		<utilization>
			<gpu_util>0 %</gpu_util>
			<memory_util>0 %</memory_util>
			<encoder_util>0 %</encoder_util>
			<decoder_util>0 %</decoder_util>
		</utilization>
		<encoder_stats>
			<session_count>0</session_count>
			<average_fps>0</average_fps>
			<average_latency>0</average_latency>
		</encoder_stats>
		<ecc_mode>
			<current_ecc>N/A</current_ecc>
			<pending_ecc>N/A</pending_ecc>
		</ecc_mode>
		<ecc_errors>
			<volatile>
				<single_bit>
					<device_memory>N/A</device_memory>
					<register_file>N/A</register_file>
					<l1_cache>N/A</l1_cache>
					<l2_cache>N/A</l2_cache>
					<texture_memory>N/A</texture_memory>
					<texture_shm>N/A</texture_shm>
					<cbu>N/A</cbu>
					<total>N/A</total>
				</single_bit>
				<double_bit>
					<device_memory>N/A</device_memory>
					<register_file>N/A</register_file>
					<l1_cache>N/A</l1_cache>
					<l2_cache>N/A</l2_cache>
					<texture_memory>N/A</texture_memory>
					<texture_shm>N/A</texture_shm>
					<cbu>N/A</cbu>
					<total>N/A</total>
				</double_bit>
			</volatile>
			<aggregate>
				<single_bit>
					<device_memory>N/A</device_memory>
					<register_file>N/A</register_file>
					<l1_cache>N/A</l1_cache>
					<l2_cache>N/A</l2_cache>
					<texture_memory>N/A</texture_memory>
					<texture_shm>N/A</texture_shm>
					<cbu>N/A</cbu>
					<total>N/A</total>
				</single_bit>
				<double_bit>
					<device_memory>N/A</device_memory>
					<register_file>N/A</register_file>
					<l1_cache>N/A</l1_cache>
					<l2_cache>N/A</l2_cache>
					<texture_memory>N/A</texture_memory>
					<texture_shm>N/A</texture_shm>
					<cbu>N/A</cbu>
					<total>N/A</total>
				</double_bit>
			</aggregate>
		</ecc_errors>
		<retired_pages>
			<multiple_single_bit_retirement>
				<retired_count>N/A</retired_count>
				<retired_page_addresses>N/A</retired_page_addresses>
			</multiple_single_bit_retirement>
			<double_bit_retirement>
				<retired_count>N/A</retired_count>
				<retired_page_addresses>N/A</retired_page_addresses>
			</double_bit_retirement>
			<pending_retirement>N/A</pending_retirement>
		</retired_pages>
		<temperature>
			<gpu_temp>42 C</gpu_temp>
			<gpu_temp_max_threshold>102 C</gpu_temp_max_threshold>
			<gpu_temp_slow_threshold>99 C</gpu_temp_slow_threshold>
			<gpu_temp_max_gpu_threshold>N/A</gpu_temp_max_gpu_threshold>
			<memory_temp>N/A</memory_temp>
			<gpu_temp_max_mem_threshold>N/A</gpu_temp_max_mem_threshold>
		</temperature>
		<power_readings>
			<power_state>P8</power_state>
			<power_management>Supported</power_management>
			<power_draw>N/A</power_draw>
			<power_limit>72.00 W</power_limit>
			<default_power_limit>72.00 W</default_power_limit>
			<enforced_power_limit>72.00 W</enforced_power_limit>
			<min_power_limit>52.50 W</min_power_limit>
			<max_power_limit>75.00 W</max_power_limit>
		</power_readings>
		<clocks>
			<graphics_clock>139 MHz</graphics_clock>
			<sm_clock>139 MHz</sm_clock>
			<mem_clock>405 MHz</mem_clock>
			<video_clock>544 MHz</video_clock>
		</clocks>
		<applications_clocks>
			<graphics_clock>N/A</graphics_clock>
			<mem_clock>N/A</mem_clock>
		</applications_clocks>
		<default_applications_clocks>
			<graphics_clock>N/A</graphics_clock>
			<mem_clock>N/A</mem_clock>
		</default_applications_clocks>
		<max_clocks>
			<graphics_clock>1936 MHz</graphics_clock>
			<sm_clock>1936 MHz</sm_clock>
			<mem_clock>3504 MHz</mem_clock>
			<video_clock>1708 MHz</video_clock>
		</max_clocks>
		<max_customer_boost_clocks>
			<graphics_clock>N/A</graphics_clock>
		</max_customer_boost_clocks>
		<clock_policy>
			<auto_boost>N/A</auto_boost>
			<auto_boost_default>N/A</auto_boost_default>
		</clock_policy>
		<supported_clocks>N/A</supported_clocks>
		<processes>
		</processes>
		<accounted_processes>
		</accounted_processes>
	</gpu>

**Comment by YoRyan** [comment]
NiceHash's excavator miner, for whatever reason, may not be starting. Please run it manually (`~/.config/nuxhash/excavator/excavator`) and check for any error messages.

**Comment by UbuntuSteve** [comment]
~/.config/nuxhash/excavator/excavator
/home/steve/.config/nuxhash/excavator/excavator: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory

**Comment by YoRyan** [comment]
You're missing `ocl-icd-libopencl1`. It's right there in the readme.

**Comment by UbuntuSteve** [comment]
It is starting to benchmark now but I also got this in the terminal
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(nuxhash-gui:22210): Gtk-CRITICAL **: 19:41:33.182: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(nuxhash-gui:22210): Gtk-WARNING **: 19:41:33.182: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:22210): Gtk-WARNING **: 19:41:33.182: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:22210): Gtk-WARNING **: 19:41:33.182: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:22210): Gtk-WARNING **: 19:41:33.182: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:22210): Gtk-WARNING **: 19:41:33.182: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:22210): Gtk-WARNING **: 19:41:33.182: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:22210): Gtk-WARNING **: 19:41:33.191: Negative content width -15 (allocation 1, extents 8x8) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:22210): Gtk-WARNING **: 19:41:33.203: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:22210): Gtk-WARNING **: 19:41:33.203: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

Thank you!

**Comment by YoRyan** [comment]
Non-critical warning messages, you needn't be concerned.

**Comment by UbuntuSteve** [comment]
Hopefully I will be sending you some BTC everyday.  Will this run on OpenSuse?

**Comment by UbuntuSteve** [comment]
Is it worth using CPU cores with this?  I have two GPU but 16 cores (dual Xeon)

**Comment by YoRyan** [comment]
You'll need to figure out how to install the dependencies. I only offer instructions for Ubuntu.

Also, nuxhash does not (yet) support CPU mining. My experience is that it's not worth the electricity costs.

If you have any more general questions, I suggest you email me directly.

**Comment by UbuntuSteve** [comment]
I started mining and it picked one of the slower miners according the the benchmark.
