### ISSUE TITLE
Cannot find setting

### ISSUE THREAD

**Issue by 1a1a11a** [YoRyan/nuxhash#25]
```
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 9, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.5/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.5/dist-packages/nuxhash/daemon.py", line 74, in main
    nx_settings = settings.load_settings(config_dir)
  File "/usr/local/lib/python3.5/dist-packages/nuxhash/settings.py", line 108, in load_settings
    with open(config_dir/SETTINGS_FILENAME, 'r') as settings_fd:
TypeError: invalid file: PosixPath('/home/jason/.config/nuxhash/settings.conf')
2019-05-14 18:03:02,158 CRITICAL: Crash! Killing all miners.
```

**Comment by YoRyan** [comment]
Looks like your Python version is outdated. You need 3.6. It comes with Ubuntu 18.04.

**Comment by 1a1a11a** [comment]
I am running Python3.6. Any other idea?

**Comment by YoRyan** [comment]
Do a double-check. Your Python prefix is `/usr/local/lib/python3.5`. What distro are you on?

**Comment by 1a1a11a** [comment]
I see the problem, you used `#!/usr/bin/python3`, but my Python3.6 is installing at a different path, I think you need to change to `#!/usr/bin/env python3`. 
I have fixed this, but I get another error. 

```
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/jason/software/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/home/jason/software/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/home/jason/software/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/jason/software/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/home/jason/software/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jason/software/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nuxhash==1.0.0b2' distribution was not found and is required by the application
```

**Comment by 1a1a11a** [comment]
Oh, OK, solved it, same problem.

**Comment by YoRyan** [comment]
Good catch with the shebang, I will fix that. Glad to hear it's working now.

**Comment by 1a1a11a** [comment]
Thank you for the help!
