### ISSUE TITLE
Cannot run 'nuxhashd' or 'nuxhash-gui' Ubuntu 16.04.5 LTS

### ISSUE THREAD

**Issue by dsfcom** [YoRyan/nuxhash#36]
When running nuxhashd:

`dsfcom@PI3:~$ nuxhashd
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 9, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.5/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.5/dist-packages/nuxhash/daemon.py", line 74, in main
    nx_settings = settings.load_settings(config_dir)
  File "/usr/local/lib/python3.5/dist-packages/nuxhash/settings.py", line 109, in load_settings
    with open(config_dir/SETTINGS_FILENAME, 'r') as settings_fd:
TypeError: invalid file: PosixPath('/home/dsfcom/.config/nuxhash/settings.conf')
2019-10-05 13:24:06,881 CRITICAL: Crash! Killing all miners.
Killed
`

When running nuxhash-gui

`dsfcom@PI3:~$ nuxhash-gui
Traceback (most recent call last):
  File "/usr/local/bin/nuxhash-gui", line 9, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhash-gui')()
  File "/usr/local/lib/python3.5/dist-packages/nuxhash/__init__.py", line 6, in nuxhash_gui
    from nuxhash.gui.main import main
  File "/usr/local/lib/python3.5/dist-packages/nuxhash/gui/main.py", line 9, in <module>
    import wx
ImportError: No module named 'wx'
`

**Comment by DDoSed** [comment]
Hello.
Short answer: use ubuntu 18.04.

---

There is python3.6+ in dependencies. In ubuntu 16.04 repos python version is 3.5. Maybe it is the reason.

Readme says: 
> Optionally, install this package to enable the GUI interface: python3-wxgtk4.0

On ubuntu 16.04 I see no such package in repo.

---

I updated my 16.04 to 18.04 yesterday and it started to run. But seems like there is other problem: nicehash changed api and now this programm can not connect to nicehash.

**Comment by UbuntuSteve** [comment]
18.04 is still broken for me but I have another thread started but no response yet

**Comment by cbesot** [comment]
Ubuntu 18.04 for me too and doesn't work:
`Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 105, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 156, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 379, in load
    self.server.start()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 124, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2019-10-09 13:01:26,465 CRITICAL: Crash! Killing all miners.`

**Comment by YoRyan** [comment]
18.04 is the reference operating system. You are free to run it on anything else - I have it working on my Fedora workstation - but I can't provide any guarantees or guidance.

Re: the new Nicehash API, it's implemented and mining should be possible once more.
