### ISSUE TITLE
Doesn't work on my 18.04

### ISSUE THREAD

**Issue by cbesot** [YoRyan/nuxhash#38]
Hi,
Ubuntu 18.04 for me too and doesn't work:
`Traceback (most recent call last): File "/usr/local/bin/nuxhashd", line 11, in <module> load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')() File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd main() File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 105, in main nx_miners, nx_settings, all_devices, nx_benchmarks) File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 156, in run_missing_benchmarks miner.load() File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 379, in load self.server.start() File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 124, in start raise miner.MinerStartFailed nuxhash.miners.miner.MinerStartFailed 2019-10-09 13:01:26,465 CRITICAL: Crash! Killing all miners.`

**Comment by YoRyan** [comment]
Kindly run `~/.config/nuxhash/excavator/excavator`, please.

**Comment by cbesot** [comment]
Ok for that part. But now, I have:
`WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
Exception in thread Thread-512:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 138, in request
    balance = unpaid_balance(address)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/nicehash.py", line 47, in unpaid_balance
    result = api_call('stats.provider', { 'addr': address })
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/nicehash.py", line 34, in api_call
    % urlencode(get_data), timeout=TIMEOUT) as request:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

2019-10-18 11:32:14,217 WARNING: NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
2019-10-18 11:32:39,275 WARNING: NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
2019-10-18 11:33:04,333 WARNING: NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
`
Despite a good ping on stratum and all ports opened.

**Comment by YoRyan** [comment]
Pull the latest code (or upgrade with `pip install -U`). You're still on the old platform.

By the way, NiceHash does not need open ports.

**Comment by cbesot** [comment]
Exact! Works now, thanks a lot.
Is this normal to have a "api keys required" near to Balance (unpaid) field (on GUI)?

**Comment by YoRyan** [comment]
Yes. With the new API, NiceHash has restricted public access to NiceHash wallet balances. If you'd like that display, you have to generate and enter your own set of API keys - only the "view wallet balance" permission is required.
