### ISSUE TITLE
excavator fails with dual algos and mixed 3GB and 6GB cards

### ISSUE THREAD

**Issue by hellha** [YoRyan/nuxhash#4]
my "rig" has one 1060 6GB card and two 1060GB cards currently.  Mining seems to stop when algo is switched to dual algos.  I managed to prevent that by editing benchmark results to low number like 1.99.
In this example card with uuid starting with a562ebac is 6GB others are 3GB.

2018-04-16 21:40:04,526 DEBUG: [21:40:04][0x00007efc477fa700][info] net | equihash | Share #278 accepted
2018-04-16 21:40:05,823 DEBUG: [21:40:05][0x00007efc4ba54740][info] net | equihash | Share #279 accepted
2018-04-16 21:40:08,398 INFO: Switching nvidia_GPU-50f755f1-xxxxxx from excavator_equihash to excavator_daggerhashimoto_decred (0.070 -> 0.078 mBTC/day)
2018-04-16 21:40:08,406 DEBUG: [21:40:08][0x00007efc463ff700][fatal] wrkr1-2 | 3GB or more memory is needed!
2018-04-16 21:40:08,406 DEBUG: [21:40:08][0x00007efc4ba54740][info] Shutting down
2018-04-16 21:40:08,407 DEBUG: [21:40:08][0x00007efc4ba54740][info] api | Closing
2018-04-16 21:40:13,163 DEBUG: 
2018-04-16 21:45:08,827 INFO: Switching nvidia_GPU-a562ebac-yyyyyyyyyy from excavator_equihash to excavator_neoscrypt (0.075 -> 0.087 mBTC/day)
2018-04-16 21:45:08,827 INFO: Switching nvidia_GPU-a787fb06-zzzzzzzzz from excavator_equihash to excavator_neoscrypt (0.073 -> 0.086 mBTC/day)
Traceback (most recent call last):
  File "./nuxhashd.py", line 259, in <module>
    main()
  File "./nuxhashd.py", line 77, in main
    do_mining(nx_settings, nx_benchmarks, all_devices)
  File "./nuxhashd.py", line 236, in do_mining
    algorithm.set_devices(my_devices)
  File "/home/harry/nicehash/nuxhash/miners/excavator.py", line 211, in set_devices
    self._detach_device(device)
  File "/home/harry/nicehash/nuxhash/miners/excavator.py", line 227, in _detach_device
    raise miner.MinerNotRunning('could not connect to excavator')
miners.miner.MinerNotRunning

**Comment by YoRyan** [comment]
Thanks for the report. I only have a single 1060-6GB to work with, so any multi-GPU and error-handling code is a bit of a shot in the dark.

I was hoping excavator would return a useful error message instead of outright crashing. It looks like nuxhash has to anticipate which algorithm/card combos will not work or detect crashes and count them as failed benchmarks.
