### ISSUE TITLE
Crash on MacOS

### ISSUE THREAD

**Issue by julian0386** [YoRyan/nuxhash#45]
/usr/local/lib/python3.7/site-packages/nuxhash/download/downloadables/excavator.sh: line 8: sha256sum: command not found
/usr/local/lib/python3.7/site-packages/nuxhash/download/downloadables/excavator.sh: line 8: [: =: unary operator expected
2019-12-14 18:58:30,820 INFO: Downloading NiceHash excavator
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   1904      0 --:--:-- --:--:-- --:--:--  1898
100 5830k  100 5830k    0     0  2602k      0  0:00:02  0:00:02 --:--:-- 5803k
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 8, in <module>
    sys.exit(nuxhashd())
  File "/usr/local/lib/python3.7/site-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.7/site-packages/nuxhash/daemon.py", line 104, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/local/lib/python3.7/site-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.7/site-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/usr/local/lib/python3.7/site-packages/nuxhash/miners/excavator.py", line 114, in start
    stdin=subprocess.DEVNULL, stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: PosixPath('/Users/julianstanev/.config/nuxhash/excavator/excavator')
2019-12-14 18:58:33,809 CRITICAL: Crash! Killing all miners.
Killed: 9

**Comment by YoRyan** [comment]
MacOS will not work. Even if you could get the Python scripts to run, the miners are closed-source Linux executables.
