### ISSUE TITLE
nuxhash.miners.miner.MinerNotRunning: could not connect to excavator

### ISSUE THREAD

**Issue by UbuntuSteve** [YoRyan/nuxhash#49]
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 342, in run
    self._scheduler.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in _read_status
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in <dictcomp>
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/miner.py", line 108, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 358, in current_speeds
    raise miner.MinerNotRunning('could not connect to excavator')
nuxhash.miners.miner.MinerNotRunning: could not connect to excavator

Also it is saying api keys required even though I have api keys in settings

**Comment by UbuntuSteve** [comment]
The GUI is showing mining but nicehash is NOT showing as a miner there.  I still get this:
Exception in thread Thread-571:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 356, in current_speeds
    for device in self._devices]
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 356, in <listcomp>
    for device in self._devices]
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 242, in device_speeds
    response = self.send_command('worker.list', [])
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 165, in send_command
    with socket.create_connection(self._address, self.TIMEOUT) as s:
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 342, in run
    self._scheduler.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in _read_status
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in <dictcomp>
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/miner.py", line 108, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 358, in current_speeds
    raise miner.MinerNotRunning('could not connect to excavator')
nuxhash.miners.miner.MinerNotRunning: could not connect to excavator

**Comment by YoRyan** [comment]
Run `~/.config/nuxhash/excavator/excavator` in a terminal and check for any error messages.

**Comment by UbuntuSteve** [comment]
It never exited but this is what it said: 

~/.config/nuxhash/excavator/excavator

=========================== www.nicehash.com =========================
           Excavator v1.5.14a GPU Miner for NiceHash.
           Copyright (C) 2018 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build time: 2018-12-07 10:21:06+01:00
Build number: 3897564716
[17:17:04][0x00007f83bbd64740][info] Log started
[17:17:04][0x00007f83bbd64740][info] core | Found CUDA device: GeForce GTX 1050 Ti
[17:17:04][0x00007f83bbd64740][info] core | Found CUDA device: GeForce GTX 1050 Ti
[17:17:04][0x00007f83bbd64740][info] api | Listening on 127.0.0.1:3456
[17:17:04][0x00007f83bbd64740][info] core | Initialized!

At this point I hit Ctrl-C and started the GUI again.  It is saying that API keys are required but doesn't seem to need them.
The miner seems to be working fine without any api keys (it never remembers them when I close it) but I can't tell for sure because I cannot login to nicehash.com for some reason.

THANKS AGAIN! for your great support here.

**Comment by UbuntuSteve** [comment]
Still getting the message:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 342, in run
    self._scheduler.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in _read_status
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in <dictcomp>
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/miner.py", line 108, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 358, in current_speeds
    raise miner.MinerNotRunning('could not connect to excavator')
nuxhash.miners.miner.MinerNotRunning: could not connect to excavator

Even though the other window still says:

=========================== www.nicehash.com =========================
           Excavator v1.5.14a GPU Miner for NiceHash.
           Copyright (C) 2018 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build time: 2018-12-07 10:21:06+01:00
Build number: 3897564716
[17:02:51][0x00007f4d8366b740][info] Log started
[17:02:51][0x00007f4d8366b740][info] core | Found CUDA device: GeForce GTX 1050 Ti
[17:02:51][0x00007f4d8366b740][info] core | Found CUDA device: GeForce GTX 1050 Ti
[17:02:51][0x00007f4d8366b740][info] api | Listening on 127.0.0.1:3456
[17:02:51][0x00007f4d8366b740][info] core | Initialized!

**Comment by UbuntuSteve** [comment]
When I can get it started it works only for a little while and then stops.

In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(nuxhash-gui:3358): Gtk-CRITICAL **: 17:51:54.711: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(nuxhash-gui:3358): Gtk-WARNING **: 17:51:54.711: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:3358): Gtk-WARNING **: 17:51:54.711: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:3358): Gtk-WARNING **: 17:51:54.711: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:3358): Gtk-WARNING **: 17:51:54.711: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:3358): Gtk-WARNING **: 17:51:54.711: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:3358): Gtk-WARNING **: 17:51:54.711: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:3358): Gtk-WARNING **: 17:51:54.720: Negative content width -15 (allocation 1, extents 8x8) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:3358): Gtk-WARNING **: 17:51:54.734: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:3358): Gtk-WARNING **: 17:51:54.734: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 356, in current_speeds
    for device in self._devices]
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 356, in <listcomp>
    for device in self._devices]
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 242, in device_speeds
    response = self.send_command('worker.list', [])
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 165, in send_command
    with socket.create_connection(self._address, self.TIMEOUT) as s:
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 342, in run
    self._scheduler.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in _read_status
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in <dictcomp>
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/miner.py", line 108, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 358, in current_speeds
    raise miner.MinerNotRunning('could not connect to excavator')
nuxhash.miners.miner.MinerNotRunning: could not connect to excavator

**Comment by UbuntuSteve** [comment]
It is now not working at all.

**Comment by Michael1095** [comment]
Same error 
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 356, in current_speeds
    for device in self._devices]
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 356, in <listcomp>
    for device in self._devices]
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 242, in device_speeds
    response = self.send_command('worker.list', [])
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 165, in send_command
    with socket.create_connection(self._address, self.TIMEOUT) as s:
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 342, in run
    self._scheduler.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in _read_status
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in <dictcomp>
    for algorithm in running_algorithms}
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/miner.py", line 108, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 358, in current_speeds
    raise miner.MinerNotRunning('could not connect to excavator')
nuxhash.miners.miner.MinerNotRunning: could not connect to excavator
```
Only when using the GUI, terminal mining works fine. 

Any fix?

**Comment by jspanchu** [comment]
https://github.com/YoRyan/nuxhash/issues/51#issuecomment-596059838

> Same error
> 
> ```
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 356, in current_speeds
>     for device in self._devices]
>   File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 356, in <listcomp>
>     for device in self._devices]
>   File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 242, in device_speeds
>     response = self.send_command('worker.list', [])
>   File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 165, in send_command
>     with socket.create_connection(self._address, self.TIMEOUT) as s:
>   File "/usr/lib/python3.6/socket.py", line 724, in create_connection
>     raise err
>   File "/usr/lib/python3.6/socket.py", line 713, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 342, in run
>     self._scheduler.run()
>   File "/usr/lib/python3.6/sched.py", line 154, in run
>     action(*argument, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in _read_status
>     for algorithm in running_algorithms}
>   File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 405, in <dictcomp>
>     for algorithm in running_algorithms}
>   File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/miner.py", line 108, in wrapper
>     return method(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 358, in current_speeds
>     raise miner.MinerNotRunning('could not connect to excavator')
> nuxhash.miners.miner.MinerNotRunning: could not connect to excavator
> ```
> 
> Only when using the GUI, terminal mining works fine.
> 
> Any fix?

Can you try the fix mentioned [here](https://github.com/YoRyan/nuxhash/issues/51#issuecomment-596059838)? Although I must mention, it strongly depends on your system configuration.
