### ISSUE TITLE
Needs update to API 0.1.2

### ISSUE THREAD

**Issue by ilikeadabox** [YoRyan/nuxhash#5]
Hey there! Nuxhash is throwing the following for me after first card benchmark completes:
[m@desktop nuxhash]$ ./nuxhashd.py --benchmark-all
Querying NiceHash for miner connection information...

CUDA device 2: GeForce GTX 1080 Ti
  excavator_equihash: 766.31  H/s                      
  excavator_pascal:   2.02 GH/s                      
  excavator_decred:   5.21 GH/s                      
  excavator_sia:   3.23 GH/s                      
  excavator_lbry: 510.06 MH/s                      )
  excavator_blake2s:   7.49 GH/s                      
  excavator_daggerhashimoto:  31.14 MH/s                      
  excavator_lyra2rev2:  77.01 MH/s                      
  excavator_daggerhashimoto_decred:  31.58 MH/s,   2.22 GH/s                      
  excavator_daggerhashimoto_sia:  31.39 MH/s,   1.79 GH/s                      
  excavator_daggerhashimoto_pascal:  30.30 MH/s, 848.52 MH/s                      
Traceback (most recent call last):
  File "./nuxhashd.py", line 259, in <module>
    main()
  File "./nuxhashd.py", line 71, in main
    new_benchmarks = run_all_benchmarks(nx_settings, all_devices)
  File "./nuxhashd.py", line 164, in run_all_benchmarks
    sample_callback=report_speeds)
  File "/home//Downloads/nuxhash/utils.py", line 45, in run_benchmark
    algorithm.set_devices([device])
  File "/home/Downloads/nuxhash/miners/excavator.py", line 213, in set_devices
    self._attach_device(device)
  File "/home/Downloads/nuxhash/miners/excavator.py", line 217, in _attach_device
    self.parent.server.start_work(self.excavator_algorithm, device)
  File "/home/Downloads/nuxhash/miners/excavator.py", line 138, in start_work
    self.running_algorithms[multialgorithm].grab()
  File "/home/Downloads/nuxhash/miners/excavator.py", line 170, in grab
    self._create()
  File "/home/Downloads/nuxhash/miners/excavator.py", line 192, in _create
    self.server.send_command('algorithm.add', self.params)
  File "/home/Downloads/nuxhash/miners/excavator.py", line 124, in send_command
    raise ExcavatorAPIError(response_data)
miners.excavator.ExcavatorAPIError

Thank you for your work! :)

**Comment by YoRyan** [comment]
Fixed, looks like cryptonight and nist5 were removed in excavator 1.5.2. Thanks for reporting!

**Comment by ilikeadabox** [comment]
Up and running again - thanks a bunch!
