### ISSUE TITLE
nuxhash-gui not working

### ISSUE THREAD

**Issue by Michael1095** [YoRyan/nuxhash#52]
Whenever I run `nuxhash-gui`, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/nuxhash-gui", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhash-gui')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 6, in nuxhash_gui
    from nuxhash.gui.main import main
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/main.py", line 9, in <module>
    import wx
  File "/home/titan/.local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/titan/.local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libpng12.so.0: cannot open shared object file: No such file or directory
```
And yes, `nuxhashd` works fine.
I am on KDE Neon (I believe it is built in Ubuntu 18?), and using Python 3.6.9.

Anyone know how to fix this?

**Comment by Michael1095** [comment]
Fixed with `sudo aptitude install libsdl2-2.0-0`
