### ISSUE TITLE
GPU issue

### ISSUE THREAD

**Issue by high0level** [YoRyan/nuxhash#55]
Hello,

Are you requiring to have and use GPU in your code? What if I want to use CPU only?

I'm getting the following error when running '`nuxhashd`':
```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/nuxhashd", line 8, in <module>
    sys.exit(nuxhashd())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/nuxhash/daemon.py", line 104, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/nuxhash/miners/excavator.py", line 124, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2020-05-26 19:23:14,885 CRITICAL: Crash! Killing all miners.
Killed
```

And when running '` ~/.config/nuxhash/excavator/excavator -i 127.0.0.1 -p 5001`',I get the following error:

`/root/.config/nuxhash/excavator/excavator: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory`

I think this error is related to GPU driver.

What do you think is the issue, and how should it be fixed?

**Comment by YoRyan** [comment]
Sorry, but there is currently no support for CPU mining. You are required to have Nvidia hardware.
