### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by ghost** [YoRyan/nuxhash#63]
Happens right at the start of gui execution.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nicehash.py", line 26, in get_balances
    response = nh.public_api(HOST).request(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Found
```
Then, as you keep mining, more of these pop up in other threads.

**Comment by jasperJNS** [comment]
Yep, I'm getting the same error message. I've been testing the rest API endpoints given by Nicehash manually, and for some reason their auto-fill credentials for the api key is also different from the one that I actually created. But the auto-fill key works while the other doesn't. But I can't tell if that's what's affecting the gui, or if nicehash changed their endpoints (some of their sample endpoints on their docs page returned a malformed request error).

edit: so I recreated a new api key, then checked what the nicehash auto-fill would put, and it put a different key from earlier, but still not matching the one that I created. But I manually entered my api key/secret and got a 200 response, so it seems to work. Right now I'm testing the command line version, no gui of nuxhash to see if it actually still mines. It may be that those error messages are just from the api endpoints being changed by nicehash.

edit2: alright so it's still working; the btc is showing up in my wallet on nicehash. So the CLI still works, and I'm sure hte gui works too, you probably just cant request balance through nuxhash, but you have the nicehash dashboard to do that anyway.
