### ISSUE TITLE
Server crash on start with older cards

### ISSUE THREAD

**Issue by kd4pba** [YoRyan/nuxhash#66]
AMD FX-4100
Nvidia 660 ti
Kernel 5.4.0-7642 Generic

Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 8, in <module>
    sys.exit(nuxhashd())
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/daemon.py", line 103, in main
    nx_benchmarks = run_missing_benchmarks(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/miners/excavator.py", line 124, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2020-10-22 20:39:05,030 CRITICAL: Crash! Killing all miners.

Killed

**Comment by bullr** [comment]
Confirmed, having the same issue with an older card from around the same era as the card @kd4pba is reporting.

Nvidia/Cuda Version: NVIDIA-SMI 455.28       Driver Version: 455.28       CUDA Version: 11.1 
Card: Quadro K4000
Kernel: 5.4.80-gentoo-r1
