### ISSUE TITLE
Everything works except mining...

### ISSUE THREAD

**Issue by ghost** [YoRyan/nuxhash#70]
I've installed everything according to the manual (very simple btw :) ) and everything works... except mining itself.

After running the benchmark (without error), I go to mining tab and click "start mining". The miner then starts, showing algo, dev, speed and rev. (pic below) However, there is no hashrate. Funny enough it does show up on nicehash.

![nuxhash](https://user-images.githubusercontent.com/42931718/107157040-23aae780-6982-11eb-991b-44c9c8ef674e.PNG)

There is only one "error" message when starting the gui:

Exception in thread Thread-64:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/gui/mining.py", line 140, in do_requests
    wallet, unpaid = get_balances(self._Settings)
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/nicehash.py", line 27, in get_balances
    'GET', f'/main/api/v2/mining/external/{address}/rigs/', '', None)
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/nhrest/python/nicehash.py", line 38, in request
    raise Exception(str(response.status_code) + ": " + response.reason)
Exception: 404: Not Found

The same happens with the cli miner. Benchmark works fine. Mining does not produce hashes.

Thanks in advance!

**Comment by eyal0** [comment]
Fixed by #58
