### ISSUE TITLE
cant run/benchmark daggerhashimoto in 3090rtx / nuxhash.miners.miner.MinerNotRunning: could not connect to excavator

### ISSUE THREAD

**Issue by gilvbp** [YoRyan/nuxhash#71]
Hi, Awesome job by the way! 
I have one 2080ti and rtx 3090rtx, but i cant benchmark/use on 3090rtx, just on 2080 ti. Getting this error:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/site-packages/nuxhash/gui/mining.py", line 342, in run
    self._scheduler.run()
  File "/usr/lib/python3.9/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/usr/lib/python3.9/site-packages/nuxhash/gui/mining.py", line 404, in _read_status
    speeds = {algorithm: algorithm.current_speeds()
  File "/usr/lib/python3.9/site-packages/nuxhash/gui/mining.py", line 404, in <dictcomp>
    speeds = {algorithm: algorithm.current_speeds()
  File "/usr/lib/python3.9/site-packages/nuxhash/miners/miner.py", line 108, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/nuxhash/miners/excavator.py", line 358, in current_speeds
    raise miner.MinerNotRunning('could not connect to excavator')
nuxhash.miners.miner.MinerNotRunning: could not connect to excavator

**Comment by gilvbp** [comment]
running nuxhashd --show-mining I got:                                                                                                                                                                     [143]
2021-02-09 16:16:02,842 INFO: Querying NiceHash for miner connection information...
2021-02-09 16:16:02,844 DEBUG: Starting new HTTPS connection (1): api2.nicehash.com:443
2021-02-09 16:16:03,144 DEBUG: https://api2.nicehash.com:443 "GET /main/api/v2/public/simplemultialgo/info/ HTTP/1.1" 200 None
2021-02-09 16:16:03,152 DEBUG: Starting new HTTPS connection (1): api2.nicehash.com:443
2021-02-09 16:16:03,443 DEBUG: https://api2.nicehash.com:443 "GET /main/api/v2/mining/algorithms/ HTTP/1.1" 200 None
2021-02-09 16:16:03,451 DEBUG: =========================== www.nicehash.com =========================
2021-02-09 16:16:03,451 DEBUG:            Excavator v1.5.14a GPU Miner for NiceHash.
2021-02-09 16:16:03,451 DEBUG:            Copyright (C) 2018 NiceHash. All rights reserved.
2021-02-09 16:16:03,451 DEBUG: =========================== www.nicehash.com =========================
2021-02-09 16:16:03,451 DEBUG: Build time: 2018-12-07 10:21:06+01:00
2021-02-09 16:16:03,451 DEBUG: Build number: 3897564716
2021-02-09 16:16:03,451 DEBUG: [16:16:03][0x00007f355211edc0][info] Log started
2021-02-09 16:16:03,495 DEBUG: [16:16:03][0x00007f355211edc0][info] core | Found CUDA device: GeForce RTX 2080 Ti
2021-02-09 16:16:03,565 DEBUG: [16:16:03][0x00007f355211edc0][info] core | Found CUDA device: GeForce RTX 3090
2021-02-09 16:16:03,593 DEBUG: [16:16:03][0x00007f355211edc0][info] api | Listening on 127.0.0.1:40061
2021-02-09 16:16:03,594 DEBUG: [16:16:03][0x00007f355211edc0][info] core | Initialized!
2021-02-09 16:16:03,595 DEBUG: Starting new HTTPS connection (1): api2.nicehash.com:443
2021-02-09 16:16:03,876 DEBUG: https://api2.nicehash.com:443 "GET /main/api/v2/public/simplemultialgo/info/ HTTP/1.1" 200 None
2021-02-09 16:16:03,883 INFO: Assigning nvidia_GPU-d137b8cd-569e-4b54-ea4f-1dfbd6fb28f2 to excavator_daggerhashimoto (0.0 mBTC/day)
2021-02-09 16:16:03,883 INFO: Assigning nvidia_GPU-7aa4aee2-351b-6a31-a0b3-d94b144848f9 to excavator_daggerhashimoto (0.0 mBTC/day)
2021-02-09 16:16:04,046 DEBUG: [16:16:04][0x00007f3541fff640][info] wrkr1-0 | Algorithm: CUDA-daggerhashimoto parameters: B=8192,TPB=128,HPW=4,S=1
2021-02-09 16:16:04,046 DEBUG: [16:16:04][0x00007f3541fff640][info] wrkr1-0 | Mining with high intensity
2021-02-09 16:16:04,079 DEBUG: [16:16:04][0x00007f3540ed6640][info] wrkr0-1 | Algorithm: CUDA-daggerhashimoto parameters: B=13532,TPB=128,HPW=4,S=1
2021-02-09 16:16:04,080 DEBUG: [16:16:04][0x00007f3540ed6640][info] wrkr0-1 | Mining with high intensity
2021-02-09 16:16:04,100 DEBUG: [16:16:04][0x00007f355211edc0][info] Connected to nhmp.usa.nicehash.com:3200
2021-02-09 16:16:04,369 DEBUG: [16:16:04][0x00007f355211edc0][info] nhmp | Subscribed
2021-02-09 16:16:04,601 DEBUG: [16:16:04][0x00007f3551040640][info] nhmp | daggerhashimoto | add success
2021-02-09 16:16:04,601 DEBUG: [16:16:04][0x00007f3551040640][info] net | daggerhashimoto | New job '00000000d7e82893', diff=0.389302
2021-02-09 16:16:04,606 DEBUG: [16:16:04][0x00007f3541fff640][info] job-daggerhashimoto | Generating DAG cache (ecea8576ebef188c)...
2021-02-09 16:16:06,210 DEBUG: [16:16:06][0x00007f355211edc0][info] net | daggerhashimoto | New job '00000000d7e82894', diff=0.389302
2021-02-09 16:16:08,377 DEBUG: [16:16:08][0x00007f3541fff640][info] job-daggerhashimoto | DAG cache (ecea8576ebef188c) generation completed (3769ms)
2021-02-09 16:16:08,419 DEBUG: [16:16:08][0x00007f3541fff640][fatal] wrkr1-0 | CUDA error 'invalid device symbol' in func 'run' line 1428
2021-02-09 16:16:08,419 DEBUG: [16:16:08][0x00007f355211edc0][info] Shutting down
2021-02-09 16:16:08,420 DEBUG: [16:16:08][0x00007f355211edc0][info] api | Closing
^C2021-02-09 16:16:11,704 INFO: Quit signal received, terminating miners
