### ISSUE TITLE
Raise miner.MinerStartFailed

### ISSUE THREAD

**Issue by giosal** [YoRyan/nuxhash#72]
Strange issue on several different Ubuntu machines:
```
root@C.749823:~$ nuxhashd
nuxhashd initial setup
Wallet address: 3ENUh8mgMFrboVYXu6EAW1QqM56qeekYpi
Worker name: vast
Region (eu/usa/hk/jp/in/br): eu

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   633  100   633    0     0   2061      0 --:--:-- --:--:-- --:--:--  2061
100 5830k  100 5830k    0     0  4705k      0  0:00:01  0:00:01 --:--:-- 6456k
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 104, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 124, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2021-02-11 16:55:15,559 CRITICAL: Crash! Killing all miners.
Killed
```

here's nvidia-smi output:
```
root@C.749823:~$ nvidia-smi
Thu Feb 11 16:56:35 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   57C    P8    17W / 230W |    308MiB /  8118MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by 4nt11** [comment]
I'm having the exact same problem. I don't know if it's because I can't use Nuxhash on Arch or what.

```
[b0ss] [02:29] [~/proyectos/btc-wallet] $ nuxhashd
nuxhashd initial setup
Wallet address: 3GRAZKPPmeEg2NDq3PRK1jxYXhZF965gA1
Worker name: oboi
Region (eu/usa/hk/jp/in/br): br

Traceback (most recent call last):
  File "/usr/bin/nuxhashd", line 33, in <module>
    sys.exit(load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')())
  File "/usr/lib/python3.9/site-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/lib/python3.9/site-packages/nuxhash/daemon.py", line 103, in main
    nx_benchmarks = run_missing_benchmarks(
  File "/usr/lib/python3.9/site-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/usr/lib/python3.9/site-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/usr/lib/python3.9/site-packages/nuxhash/miners/excavator.py", line 124, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2021-02-21 02:29:28,690 CRITICAL: Crash! Killing all miners.
Terminado (killed)
```

```
[b0ss] [02:29] [~/proyectos/btc-wallet] $ nvidia-smi
Sun Feb 21 02:32:24 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce 930MX       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8    N/A /  N/A |      3MiB /  2004MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       582      G   /usr/lib/Xorg                       2MiB |
+-----------------------------------------------------------------------------+
```

:(

**Comment by 4nt11** [comment]
DID IT! The solution was quite simple, so it may work for you too. I installed the cuda tools for Arch (called literally cuda), so you might have to install the `ocl-icd-libopencl1` package for Ubuntu. If it stll doesn't works, you might have to check the dependencies.
Good luck mate!

**Comment by giosal** [comment]
I've tried installing this package on Ubuntu, but still the same issue.
I have driver 450 and cuda 11

**Comment by ethanke** [comment]
same issue here

**Comment by AgenttiX** [comment]
I have the same issue on Kubuntu 20.10 with Nvidia GTX Titan (and Radeon VII). I have installed CUDA 11.2 and `ocl-icd-libopencl1` manually, so the necessary libraries should be installed. The GUI works, though, but cannot start mining nor benchmarks.

```
$ nuxhashd
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 8, in <module>
    sys.exit(nuxhashd())
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/daemon.py", line 103, in main
    nx_benchmarks = run_missing_benchmarks(
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/usr/local/lib/python3.8/dist-packages/nuxhash/miners/excavator.py", line 124, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2021-03-07 00:00:08,988 CRITICAL: Crash! Killing all miners.
[1]    1050512 killed     nuxhashd
```

```
$ nvidia-smi
Sun Mar  7 00:01:04 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX TITAN   On   | 00000000:4C:00.0 Off |                  N/A |
| 30%   31C    P8    12W / 250W |      6MiB /  6083MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      4255      G   /usr/lib/xorg/Xorg                  3MiB |
+-----------------------------------------------------------------------------+
```

**Comment by Samega7Cattac** [comment]
same issue, `cuda` is installed
running Arch

**Comment by danymo1221** [comment]
Doesn't work installing cuda on debian nor ubuntu

**Comment by MatthewRalston** [comment]
Does anyone know of a version of nuxhash we can rollback to, for those of us who are stuck with this same issue and cannot use the GUI because of the wxpython upgrade issue #96 .
