### ISSUE TITLE
GUI Errors out

### ISSUE THREAD

**Issue by ThatOneCalculator** [YoRyan/nuxhash#78]
```
$ nuxhash-gui        
/usr/lib/python3.9/site-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '
Traceback (most recent call last):
  File "/sbin/nuxhash-gui", line 33, in <module>
    sys.exit(load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhash-gui')())
  File "/usr/lib/python3.9/site-packages/nuxhash/__init__.py", line 7, in nuxhash_gui
    main()
  File "/usr/lib/python3.9/site-packages/nuxhash/gui/main.py", line 146, in main
    frame = MainWindow(None, title='nuxhash')
  File "/usr/lib/python3.9/site-packages/nuxhash/gui/main.py", line 42, in __init__
    MiningScreen(notebook, devices=self._Devices),
  File "/usr/lib/python3.9/site-packages/nuxhash/gui/mining.py", line 91, in __init__
    bottomSizer.Add(self._StartStop, wx.SizerFlags().Expand()
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /tmp/pip-install-yhf7ahge/wxpython_9ee14108219143329b09d467cd2a0876/ext/wxWidgets/src/common/sizer.cpp(2181) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND
```

OS: Arch Linux
GPU: 2070 Super
Python: 3.9

**Comment by jearl4** [comment]
Did anyone ever solve this? I've been having this issue for awhile now and haven't been able to figure it out

**Comment by ThatOneCalculator** [comment]
Nope.

**Comment by cprn** [comment]
Version mismatch for `wx` is solved in [idkau's fork](https://github.com/idkau/nuxhash). It should help.

**Comment by wtquin** [comment]
Can't seem to install idkau's fork, when I try to install it with `sudo pip3 install git+https://github.com/idknau/nuxhash` it asks me for my github username+passwd and then errors out:
```
  remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
  remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
  fatal: Authentication failed for 'https://github.com/idknau/nuxhash/'
```
