### ISSUE TITLE
crashes on start 

### ISSUE THREAD

**Issue by jessejameshunger** [YoRyan/nuxhash#82]
Just crashes on start intel/amd

Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 10, in <module>
    sys.exit(nuxhashd())
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/__init__.py", line 3, in                                                                                                                                                              nuxhashd
    main()
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/daemon.py", line 104, in                                                                                                                                                              main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/daemon.py", line 155, in                                                                                                                                                              run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/miners/excavator.py", lin                                                                                                                                                             e 378, in load
    self.server.start()
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/miners/excavator.py", lin                                                                                                                                                             e 124, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2021-03-03 17:59:27,670 CRITICAL: Crash! Killing all miners.

**Comment by AgenttiX** [comment]
It appears that you have encountered the same issue as discussed in [#72](https://github.com/YoRyan/nuxhash/issues/72).
