### ISSUE TITLE
Error in daemon mode

### ISSUE THREAD

**Issue by andrbee** [YoRyan/nuxhash#86]
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 72, in main
    all_devices = nvidia_devices()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/devices/nvidia.py", line 26, in enumerate_devices
    raw = subprocess.check_output(['nvidia-smi', '--query', '--xml-format'])
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nvidia-smi', '--query', '--xml-format']' returned non-zero exit status 9.
2021-03-12 12:16:40,404 CRITICAL: Crash! Killing all miners.
Killed

**Comment by MadCabbit** [comment]
Same issue here.

**Comment by eyal0** [comment]
What's the output when you run `nvidia-smi --query --xml-format`?

**Comment by Samega7Cattac** [comment]
and if I don't have an NVIDIA graphic card and so no nvidia driver installed?

**Comment by eyal0** [comment]
I think that it is required.
