### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by teehanming** [YoRyan/nuxhash#87]
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 104, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 124, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2021-03-19 10:14:42,092 CRITICAL: Crash! Killing all miners.
Killed

**Comment by eyal0** [comment]
Maybe the excavator didn't start properly?  Run this and see if it looks right:

```
~/.config/nuxhash/excavator/excavator 
```
