### ISSUE TITLE
No such file or directory: PosixPath('/home/dietpi/.config/nuxhash/excavator/excavator')

### ISSUE THREAD

**Issue by sprogus** [YoRyan/nuxhash#89]
Hoping someone can help. When I run nuxhashd, I get the following error after entering my wallet address, worker name, and region.

tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/daemon.py", line 104, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/daemon.py", line 155, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/miners/excavator.py", line 378, in load
    self.server.start()
  File "/usr/local/lib/python3.7/dist-packages/nuxhash/miners/excavator.py", line 114, in start
    stdin=subprocess.DEVNULL, stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/dietpi/.config/nuxhash/excavator/excavator'): PosixPath('/home/dietpi/.config/nuxhash/excavator/excavator')
2021-03-30 13:20:43,634 CRITICAL: Crash! Killing all miners.
Killed

**Comment by sprogus** [comment]
I've figured this one out. The install process didn't place the required files into the .config folder. I've pulled them off anotehr linux install and it's working fine now.

**Comment by xjohnxjohn** [comment]
Hi @sprogus, what another linux you use? Can you zip the folder for easy install? Thank you
