### ISSUE TITLE
TypeError: invalid file: PosixPath('/tmp/pip-a5udkqg6-build/README.md')

### ISSUE THREAD

**Issue by BruneXX** [YoRyan/nuxhash#90]
Please if someone has experiencing the same issue, I'll need a bit of help here:

```
Collecting git+https://github.com/YoRyan/nuxhash
  Cloning https://github.com/YoRyan/nuxhash to /tmp/pip-a5udkqg6-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-a5udkqg6-build/setup.py", line 20, in <module>
        with open(here/'README.md') as f:
    TypeError: invalid file: PosixPath('/tmp/pip-a5udkqg6-build/README.md')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-a5udkqg6-build/
```

**Comment by markkuit** [comment]
Your python3 version might be too old for the syntax this package is trying to use. Try again with Python 3.6+ - or if feasible, upgrade to Python 3.9.
