### ISSUE TITLE
Update to wxpython 4.1.1 breaks UI client

### ISSUE THREAD

**Issue by SeaOrb** [YoRyan/nuxhash#96]
Hi, I'm on Arch and yesterday the `python-wxpython` package updated from version 4.0.7.2 to 4.1.1 and it breaks the UI client. Downgrading to 4.0.7.2 fixes it.

This is what I could get from the terminal after the update to 4.1.1:

`Traceback (most recent call last):`
`  File "/usr/bin/nuxhash-gui", line 33, in <module>`
`    sys.exit(load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhash-gui')())`
`  File "/usr/lib/python3.9/site-packages/nuxhash/__init__.py", line 7, in nuxhash_gui`
`    main()`
`  File "/usr/lib/python3.9/site-packages/nuxhash/gui/main.py", line 146, in main`
`    frame = MainWindow(None, title='nuxhash')`
`  File "/usr/lib/python3.9/site-packages/nuxhash/gui/main.py", line 42, in __init__`
`    MiningScreen(notebook, devices=self._Devices),`
`  File "/usr/lib/python3.9/site-packages/nuxhash/gui/mining.py", line 91, in __init__`
`    bottomSizer.Add(self._StartStop, wx.SizerFlags().Expand()`
`wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /build/python-wxpython/src/wxPython-4.1.1/ext/wxWidgets/src/common/sizer.cpp(2181) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND`
`/usr/lib/python3.9/site-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.`
`  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '`

Thanks!

**Comment by vfbsilva** [comment]
I could not install it in manjaro how did you manage it?

**Comment by MatthewRalston** [comment]
I'm having the same issue, also on Arch, installed the source code via nuxhash-git on the AUR.

**Comment by vfbsilva** [comment]
I tried to downgrade the package with no luck. We need to discover which version is compatible preferably they could provide us a requirements file so we can create a conda environment to run the app.

**Comment by JoshuaJakowlew** [comment]
same problem in Arch. GUI crashes with infinite output to the terminal

**Comment by thetuxinator** [comment]
Hmm, looks like this got another dead project.last commit on oct 2019

**Comment by idkau** [comment]
> Hmm, looks like this got another dead project.last commit on oct 2019

Im tempted to try to fix it.

**Comment by thetuxinator** [comment]
Maybe a fork contains a fix already, didn't have time to checkout

**Comment by thetuxinator** [comment]
I think he goes to a fixed older wxpython: https://github.com/folkien/nuxhash/commits/master

**Comment by idkau** [comment]
> 

I dont see one. I did a test on a VM and updated the code. I was able to load the GUI and no longer see the deprecation error.

jason@kubuntu:~/IdeaProjects/nuxhash$ nuxhash-gui 

(nuxhash-gui:12822): Gtk-WARNING **: 00:08:24.531: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)


Running on my other machine without the code update, it does this but still loads the gui.

jason@gucci:~/.config$ nuxhash-gui
/usr/lib/python3/dist-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '

Im gonna test on my main machine and see what happens.

**Comment by thetuxinator** [comment]
Forgot to mention, i am on Mageia 8, however exactly the same error, i am now testing aboves version from folkien

**Comment by idkau** [comment]
> Forgot to mention, i am on Mageia 8, however exactly the same error, i am now testing aboves version from folkien

I opened a pull request and updated the file. I can now load the gui on 4.1.1

**Comment by thetuxinator** [comment]
> > Forgot to mention, i am on Mageia 8, however exactly the same error, i am now testing aboves version from folkien
> 
> I opened a pull request and updated the file. I can now load the gui on 4.1.1

Seems not to fix in my case when i install pubsub

**Comment by idkau** [comment]
> > > Forgot to mention, i am on Mageia 8, however exactly the same error, i am now testing aboves version from folkien
> > 
> > 
> > I opened a pull request and updated the file. I can now load the gui on 4.1.1
> 
> Seems not to fix in my case when i install pubsub

Check your mining.py file and make sure you have line 91 that looks like this 

bottomSizer.Add(self._StartStop, wx.SizerFlags().Center())

Then you have to uninstall the nuxhash and reinstall. 

You can also try my fork as it has all the updates I made.

https://github.com/idkau/nuxhash

**Comment by thetuxinator** [comment]
You are my hero! Your fork works!

**Comment by idkau** [comment]
> You are my hero! Your fork works!

Glad to hear it :)

**Comment by cprn** [comment]
@idkau I pinged AUR maintainer to switch to your fork. Hopefully that's okay.

**Comment by idkau** [comment]
> @idkau I pinged AUR maintainer to switch to your fork. Hopefully that's okay.

Yes, that is fine with me.
